### PR TITLE
inbox for philip

### PR DESCRIPTION
**Pull request by Joeyrsp**

### CODE REVIEW

**Comment by Joeyrsp** [comment]
ive found a couple of minor bugs with the inbox stuff but ill include those in my next pr for philips stuff

**Comment by xpatiate** [comment]
Thanks Joey, looks good! I've checked out your changes and had a quick look but not really sure how to try them out. Could you add a section to the README or just some code comments to give a quick description on how the inbox works?

**Comment by Joeyrsp** [comment]
ill put some info in the README

**Comment by Joeyrsp** [comment]
ive updated the README with some info on the inbox.

**Pull request merged**
