### PR TITLE
added listing under review declaration type & added link field to add declaration page

### PR DESCRIPTION
**Pull request by Joeyrsp**
listing under review provides admins with a flag to review the declaration listing of an area. the addition of the link field to the add declaration page required some hackery in the form and view. im not super happy with the way it works but i wasnt sure how else to do it

### CODE REVIEW

**Comment by xpatiate** [comment]
Hi Joey, yeah I found it wasn't at all obvious how to add a dependent link when creating a new object. The way I did it is in the `structure_child` and `area_child` methods, do you think making the POST object mutable is a better approach? Would your change to LinkForm affect those existing methods?

**Review by xpatiate — APPROVED** [review]
hi @Joeyrsp I had a closer look at your changes and ran a quick test to confirm that the change to LinkForm doesn't affect the existing add-link-to-new-object functionality for area and structure - all seems fine so I'll merge this now

**Comment by Joeyrsp** [comment]
Sorry I didn't see those messages. As I've just found out I've been working on a fork missing your last commit so I didn't see the way you had implemented it. If you'd prefer to keep things consistent I can revert my changes and use your system.

**Comment by xpatiate** [comment]
No worries - if you add yourself as a watcher on this repo I think github will notify you when there are comments.

I do think it would be good for the various pages to use a consistent method for adding a link to a new object, but I don't know which method is better and don't have the brain space to form an opinion on it right now :) Happy to leave it as is for the time being.

Definitely please update to the latest master whenever you start work on a new set of changes, especially if/when we are both working on stuff at the same time, so we avoid merge conflicts.

**Pull request merged**
